### ISSUE TITLE
Add shortlinks to changelog

### ISSUE THREAD

**Issue by contaoacademy** [contao/to.contao.org#5]
```
changelog44:
    en: https://github.com/contao/contao/blob/4.4/CHANGELOG.md

changelog49
    en: https://github.com/contao/contao/blob/4.9/CHANGELOG.md

changelog
    en: https://github.com/contao/contao/blob/4.10/CHANGELOG.md
```

`to.contao.org/changelog` should always redirect to the latest contao version.

**Comment by leofeyer** [comment]
Not sure if we really need that. If we go for it, I would prefer `changelog/4.4` over `changelog44`. And we should probably add links for all versions.

**Comment by Toflar** [comment]
I don't see why these would make sense, really...

**Comment by contaoacademy** [comment]
> I don't see why these would make sense, really...

I used the links in the last few days more often. If you don't think this give a value, then close the ticket.
I can live fine without it and add it to my personal favorites 😁

**Comment by fritzmg** [comment]
I am in favour.

Also currently it is rather difficult to find the changelog. Neither a [Google search](https://www.google.com/search?q=contao+changelog) nor a [contao.org serach](https://contao.org/en/search.html?keywords=changelog) will currently give you any usable results.

**Comment by Toflar** [comment]
Okay, then please create a PR but mind @leofeyer's comment :) Also, you don't need to specify any language.

**Comment by netzarbeiter** [comment]
https://github.com/contao/to.contao.org/pull/6

**Comment by Toflar** [comment]
Done, thx @netzarbeiter
